### ISSUE TITLE
Training data description

### ISSUE THREAD

**Issue by NonaryR** [glami/glami-1m#1]
Hello! After downloading this zip archive - [GLAMI-1M Dataset (the default 228x298 version) here (1 zip file of 11GB)](https://zenodo.org/record/7326406/files/GLAMI-1M-dataset.zip?download=1) I can find only `GLAMI-1M-test.csv` with ~100k rows and nothing about train data. Where I can find it?

**Comment by thonic** [comment]
Hi,

thank you for letting me know, there should be both files, we will look
into it right away and let you know.

  Antonín

út 6. 12. 2022 v 20:18 odesílatel Rustam G ***@***.***>
napsal:

**Comment by thonic** [comment]
We have downloaded the dataset twice to be sure and both times the file `GLAMI-1M-train.csv` was included in the archive. If the direct download/extraction fails for you, you can also download the dataset with Python:
https://github.com/glami/glami-1m#how-to-download-glami-1m-programmatically

**Comment by vackosar** [comment]
The python approach is recommended as you can get directly dataframe. But you can also list files within the zip in this way: `unzip -l GLAMI-1M-dataset.zip` and you can search for the train file in this way `unzip -l GLAMI-1M-dataset.zip |grep train |grep train`.

**Comment by vackosar** [comment]
If you don't know how to do any of above, don't hesitate to ask questions in this thread.

**Comment by NonaryR** [comment]
Yes, I'm capable to do this =)
You downloaded zip archive which you provide in your readme or do it programmatically? If second, then you should check this [GLAMI-1M Dataset (the default 228x298 version) here (1 zip file of 11GB)](https://zenodo.org/record/7326406/files/GLAMI-1M-dataset.zip?download=1), there is no train file

**Comment by thonic** [comment]
I went directly to the link you provided (on Zenodo) and this is what I see after extraction:
```
...GLAMI-1M-dataset$ ls
GLAMI-1M-test.csv  GLAMI-1M-train.csv  images  LICENSE  NOTICE  README.txt
```
I see the training split there.

**Comment by thonic** [comment]
And it has the correct number of lines:
```
$ wc -l GLAMI-1M-train.csv 
1000001 GLAMI-1M-train.csv
```

**Comment by thonic** [comment]
I am happy to reopen the issue, but I am failing to reproduce the problem, would you mind downloading/extracting again? It might be just a corrupted archive.

**Comment by vackosar** [comment]
@NonaryR Hello, did it another download and extract solved the issue for you?

**Comment by NonaryR** [comment]
My issue is somehow related to google colab, after unzip archive there I steel can't see train file. But when I downloaded this archive locally, all files was in place

**Comment by vackosar** [comment]
I see. I am not quite sure what the problem could be in Google Colab. Perhaps your download was corrupted, which can happen. I read that the disk limit is 75GB. I also tested the Google Colab successfully, see below screenshot.
![image](https://user-images.githubusercontent.com/11373934/207397833-e0589394-69c9-4854-b5d9-38a1e547d88d.png)
